My Project: ClassSiec.cpp File Reference
ClassSiec.cpp File Reference
#include "ClassSiec.h"
Functions
template<class T >
T find_max (T *data, uint64_t size)
template<class T >
T find_min (T *data, uint64_t size)
template<class T >
T find_max (vector< T > &data)
template<class T >
T find_min (vector< T > &data)
template<class T >
T find_delta (vector< T > &data)
template<class T >
T find_sum (vector< T > &data)
template<class T >
T find_average (vector< T > &data)
template<typename Type >
void remove_duplicate (std::vector< Type > vec)
template<typename Type >
void remove_duplicate2 (std::vector< Type > vec)
int find_is_in_range (double value, double centrum, double delta)
int find_is_in_range (double value, double centrum, double left, double right)
double get_distance_1d (double x0, double x1, double box_x)
double get_distance_2d (particle *p0, particle *p1, double box_x, double box_y)
double get_distance_2d (double x0, double y0, double x1, double y1, double box_x, double box_y)
void th_to_box (particle *particle, double box_x=0.0, double box_y=0.0)
int zderzenie (particle *cz0, particle *cz1, double box_x, double box_y)
int save_to_file (std::string filename, std::string data)
void thread_RDF (ClassSiec *siec, uint64_t c1, double prec)
Function Documentation
find_average()
template<class T > T find_average (vector< T > & data)
Definition at line 79 of file ClassSiec.cpp.
find_delta()
template<class T > T find_delta (vector< T > & data)
Definition at line 51 of file ClassSiec.cpp.
Referenced by ClassSiec::get_diffusitivity_delta(), ClassSiec::get_diffusitivity_delta_ratio(), ClassSiec::get_Velocity_Autocorrelation_Function_delta(), and ClassSiec::get_Velocity_Autocorrelation_Function_delta_ratio().
find_is_in_range() [1/2]
int find_is_in_range (double value, double centrum, double delta)
Definition at line 103 of file ClassSiec.cpp.
Referenced by ClassSiec::create_hexagonal(), ClassSiec::create_honeycomb(), ClassSiec::set_momentum_to_zero(), and thread_siec().
find_is_in_range() [2/2]
int find_is_in_range (double value, double centrum, double left, double right)
Definition at line 108 of file ClassSiec.cpp.
find_max() [1/2]
template<class T > T find_max (T * data, uint64_t size)
Definition at line 3 of file ClassSiec.cpp.
find_max() [2/2]
template<class T > T find_max (vector< T > & data)
Definition at line 25 of file ClassSiec.cpp.
find_min() [1/2]
template<class T > T find_min (T * data, uint64_t size)
Definition at line 12 of file ClassSiec.cpp.
find_min() [2/2]
template<class T > T find_min (vector< T > & data)
Definition at line 38 of file ClassSiec.cpp.
find_sum()
template<class T > T find_sum (vector< T > & data)
Definition at line 69 of file ClassSiec.cpp.
get_distance_1d()
double get_distance_1d (double x0, double x1, double box_x)
Calculate the distance in box
Parameters
x0
x1
box_x
Returns
Definition at line 228 of file ClassSiec.cpp.
Referenced by particle::get_distance(), get_distance_2d(), particle::get_time_to_collision(), and zderzenie().
get_distance_2d() [1/2]
double get_distance_2d (particle * p0, particle * p1, double box_x, double box_y)
Calculate distance in 2D in box
Parameters
p0
p1
box_x
box_y
Returns
Definition at line 246 of file ClassSiec.cpp.
References get_distance_1d(), and particle::pos.
Referenced by ClassSiec::get_number_of_particles_in_radius().
get_distance_2d() [2/2]
double get_distance_2d (double x0, double y0, double x1, double y1, double box_x, double box_y)
Calculate distance in 2D in box
Parameters
x0
y0
x1
y1
box_x
box_y
Returns
Definition at line 263 of file ClassSiec.cpp.
References get_distance_1d().
remove_duplicate()
template<typename Type > void remove_duplicate (std::vector< Type > vec)
Definition at line 90 of file ClassSiec.cpp.
remove_duplicate2()
template<typename Type > void remove_duplicate2 (std::vector< Type > vec)
Definition at line 97 of file ClassSiec.cpp.
save_to_file()
int save_to_file (std::string filename, std::string data)
Save to file
Parameters
filename
data
Returns
Definition at line 1497 of file ClassSiec.cpp.
References OK.
th_to_box()
void th_to_box (particle * particle, double box_x = 0.0, double box_y = 0.0)
Repair position of particle to the box
Parameters
particle
box_x
box_y
Definition at line 924 of file ClassSiec.cpp.
References particle::pos.
Referenced by ClassSiec::fix_position(), and ClassSiec::step_all().
thread_RDF()
void thread_RDF (ClassSiec * siec, uint64_t c1, double prec)
Thread for RDF
Parameters
siec
c1
prec
Definition at line 1748 of file ClassSiec.cpp.
References ClassSiec::current_RDF, ClassSiec::get_density(), ClassSiec::get_min_radius(), ClassSiec::get_number_of_particles_in_radius(), ClassSiec::get_particles_len(), and ClassSiec::particles.
Referenced by ClassSiec::save_RDF(), and ClassSiec::save_RDF_to_array().
zderzenie()
int zderzenie (particle * cz0, particle * cz1, double box_x, double box_y)
Make collision of particles
Parameters
cz0
cz1
box_x
box_y
Returns
Definition at line 1101 of file ClassSiec.cpp.
References particle::color, particle::get_distance(), get_distance_1d(), particle::m, OK, particle::pos, particle::tlc, and particle::vel.
Referenced by ClassSiec::step_all().