My Project: ClassSiec Class Reference
ClassSiec Class Reference
#include <ClassSiec.h>
Public Member Functions
ClassSiec (void)
ClassSiec (double dt, double box_x=800.0, double box_y=600.0)
virtual ~ClassSiec (void)
int add_particle (double x, double y, double r, double vx=0.0, double vy=0.0, double maxVelocity=0.0)
int create_square (double a, double r)
int create_honeycomb (double a, double r)
int create_honeycomb (double a, double r, double density, double precision=0.01)
int create_hexagonal (double a, double r)
int create_hexagonal (double a, double r, double density, double precision)
int set_random_velocity (double multiplier=1.0)
int set_random_size (double min, double max)
int set_mass_to_radius (double ratio=1.0)
int set_mass_to_area (double ratio=1.0)
int set_mass_all (double mass=1.0)
int set_momentum_to_zero (double Ekpoz_t, double precision=0.001)
int set_particles_zero_time (void)
int set_dt (double dt)
uint64_t get_particles_len (void)
int get_particle (uint64_t nr, particle *here)
s_pair get_next_collision_particle_number (void)
double get_next_collision_particles (vector< s_pair > *ptr)
float get_time (void)
float get_temperature (void)
float get_density (void)
float get_density_real (void)
float get_packing_ratio (void)
double get_kinetic_energy (void)
uint64_t get_number_of_particles_in_radius (double r, double dr, particle *for_particle)
uint64_t get_number_of_particles_in_radius (double r, double dr)
float get_radial_distribution_function (double r, double dr, particle *for_particle, uint64_t prec=100)
float get_radial_distribution_function (double r, double dr)
float get_radial_distribution_function_theoretical (void)
float get_state_space_Boublik (void)
float get_state_space_Handerson (void)
float get_state_space_Solan (void)
float get_Velocity_Autocorrelation_Function (void)
float get_diffusivity (void)
double get_diffusitivity_delta (void)
double get_Velocity_Autocorrelation_Function_delta (void)
double get_diffusitivity_delta_ratio (void)
double get_Velocity_Autocorrelation_Function_delta_ratio (void)
double get_box_x (void)
double get_box_y (void)
double get_min_radius (void)
double get_max_radius (void)
void convert_to_box (double *x, double *y)
std::string get_box_info (std::string sep="\)
std::string get_box_info_title (std::string sep="\)
std::string get_box_info_raw (std::string sep="\)
std::string get_RDF_r (double r, double dr, uint64_t prec=100, std::string sep=" ")
std::string get_RDF_r (uint64_t prec=100, std::string sep=" ")
std::string get_static_parameters_info (std::string sep="\)
std::string get_static_parameters_title (std::string sep="\)
std::string get_static_parameters_raw (std::string sep="\)
int save_RDF (uint64_t prec=100, std::string sep=" ")
void save_RDF_to_array (vector< double > *array, uint64_t prec=100)
int fix_position (void)
int init (std::string filename)
int insert_to_file (std::string data)
int flush_file (void)
int close_file (void)
int step_all (int debug=0)
Public Attributes
vector< particle > particles
vector< particle_zero_time > particles_zero_time
vector< double > current_RDF
double distancex
double distancey
double distance
double box_x
double box_y
Detailed Description
Definition at line 105 of file ClassSiec.h.
Constructor & Destructor Documentation
ClassSiec() [1/2]
ClassSiec::ClassSiec (void)
Definition at line 354 of file ClassSiec.cpp.
References box_x, and box_y.
ClassSiec() [2/2]
ClassSiec::ClassSiec (double dt, double box_x = 800.0, double box_y = 600.0)
Constructor
Todo:
dt is deprecated
Parameters
dt -> deprecated
box_x
box_y
Definition at line 372 of file ClassSiec.cpp.
References box_x, and box_y.
~ClassSiec()
ClassSiec::~ClassSiec (void) virtual
Definition at line 383 of file ClassSiec.cpp.
References particles.
Member Function Documentation
add_particle()
int ClassSiec::add_particle (double x, double y, double r, double vx = 0.0, double vy = 0.0, double maxVelocity = 0.0)
Add particle to array
Todo:
maxVelocity is probably useless
Parameters
x
y
r
vx
vy
maxVelocity
Returns
Definition at line 432 of file ClassSiec.cpp.
References OK, and particles.
Referenced by create_hexagonal(), create_honeycomb(), and create_square().
close_file()
int ClassSiec::close_file (void)
Flush and close file
Returns
Definition at line 990 of file ClassSiec.cpp.
References OK.
Referenced by main().
convert_to_box()
void ClassSiec::convert_to_box (double * x, double * y)
Set positions to box
Parameters
x
y
Definition at line 405 of file ClassSiec.cpp.
References box_x, and box_y.
create_hexagonal() [1/2]
int ClassSiec::create_hexagonal (double a, double r)
Adds particles in the form of a hexagonal
Parameters
a
r
Returns
Definition at line 632 of file ClassSiec.cpp.
References add_particle(), box_x, box_y, and OK.
create_hexagonal() [2/2]
int ClassSiec::create_hexagonal (double a, double r, double density, double precision)
Generate hexagonal lattice with desired density
Parameters
a
r
density
precision
Returns
Definition at line 576 of file ClassSiec.cpp.
References add_particle(), box_x, box_y, find_is_in_range(), get_density_real(), OK, and particles.
create_honeycomb() [1/2]
int ClassSiec::create_honeycomb (double a, double r)
Adds particles in the form of a honeycomb
Parameters
a
r
Returns
Definition at line 477 of file ClassSiec.cpp.
References add_particle(), box_x, box_y, and OK.
Referenced by main().
create_honeycomb() [2/2]
int ClassSiec::create_honeycomb (double a, double r, double density, double precision = 0.01)
Generate honeycomb lattice with desired density
Parameters
a
r
density
precision
Returns
Definition at line 514 of file ClassSiec.cpp.
References add_particle(), box_x, box_y, find_is_in_range(), get_density_real(), OK, and particles.
create_square()
int ClassSiec::create_square (double a, double r)
Adds particles in the form of a square
Parameters
a
r
Returns
Definition at line 448 of file ClassSiec.cpp.
References add_particle(), box_x, box_y, and OK.
fix_position()
int ClassSiec::fix_position (void)
Repair positions of all particles to the box
Returns
Definition at line 936 of file ClassSiec.cpp.
References box_x, box_y, get_particles_len(), OK, particles, and th_to_box().
Referenced by main(), and step_all().
flush_file()
int ClassSiec::flush_file (void)
Definition at line 979 of file ClassSiec.cpp.
References OK.
Referenced by main(), and thread_siec().
get_box_info()
std::string ClassSiec::get_box_info (std::string sep = "\t")
Get box info -> info for save in logs
Returns
Definition at line 1511 of file ClassSiec.cpp.
References get_diffusitivity_delta(), get_diffusivity(), get_Velocity_Autocorrelation_Function(), and get_Velocity_Autocorrelation_Function_delta().
Referenced by step_all().
get_box_info_raw()
std::string ClassSiec::get_box_info_raw (std::string sep = "\t")
Get raw data of info
Parameters
sep
Returns
Definition at line 1585 of file ClassSiec.cpp.
References get_diffusitivity_delta(), get_diffusivity(), get_Velocity_Autocorrelation_Function(), and get_Velocity_Autocorrelation_Function_delta().
Referenced by step_all().
get_box_info_title()
std::string ClassSiec::get_box_info_title (std::string sep = "\t")
Return title of infos
Parameters
sep
Returns
Definition at line 1548 of file ClassSiec.cpp.
Referenced by init().
get_box_x()
double ClassSiec::get_box_x (void)
Definition at line 1454 of file ClassSiec.cpp.
References box_x.
Referenced by draw_all().
get_box_y()
double ClassSiec::get_box_y (void)
Definition at line 1458 of file ClassSiec.cpp.
References box_y.
Referenced by draw_all().
get_density()
float ClassSiec::get_density (void)
Get density particles in box
Returns
Definition at line 1161 of file ClassSiec.cpp.
References box_x, box_y, and get_particles_len().
Referenced by get_radial_distribution_function(), get_RDF_r(), get_state_space_Boublik(), get_state_space_Handerson(), get_state_space_Solan(), get_static_parameters_info(), get_static_parameters_raw(), and thread_RDF().
get_density_real()
float ClassSiec::get_density_real (void)
Get density(real) particles in box
Returns
Definition at line 1179 of file ClassSiec.cpp.
References box_x, box_y, get_particles_len(), and particles.
Referenced by create_hexagonal(), create_honeycomb(), get_static_parameters_info(), and get_static_parameters_raw().
get_diffusitivity_delta()
double ClassSiec::get_diffusitivity_delta (void)
Get diffusivity delta
Returns
Definition at line 1426 of file ClassSiec.cpp.
References find_delta().
Referenced by get_box_info(), get_box_info_raw(), get_static_parameters_info(), get_static_parameters_raw(), and thread_siec().
get_diffusitivity_delta_ratio()
double ClassSiec::get_diffusitivity_delta_ratio (void)
Get diffusivity delta ratio
Returns
Definition at line 1440 of file ClassSiec.cpp.
References find_delta(), and get_diffusivity().
Referenced by get_static_parameters_info(), and get_static_parameters_raw().
get_diffusivity()
float ClassSiec::get_diffusivity (void)
Get diffusivity
Returns
Definition at line 1417 of file ClassSiec.cpp.
Referenced by get_box_info(), get_box_info_raw(), get_diffusitivity_delta_ratio(), get_static_parameters_info(), and get_static_parameters_raw().
get_kinetic_energy()
double ClassSiec::get_kinetic_energy (void)
Get the kinetic energy of particles
Returns
Definition at line 1217 of file ClassSiec.cpp.
References get_particles_len(), and particles.
Referenced by set_momentum_to_zero().
get_max_radius()
double ClassSiec::get_max_radius (void)
Definition at line 1477 of file ClassSiec.cpp.
References get_particles_len(), and particles.
get_min_radius()
double ClassSiec::get_min_radius (void)
Definition at line 1463 of file ClassSiec.cpp.
References get_particles_len(), and particles.
Referenced by main(), step_all(), and thread_RDF().
get_next_collision_particle_number()
s_pair ClassSiec::get_next_collision_particle_number (void)
Return pair of next collision
Returns
Definition at line 861 of file ClassSiec.cpp.
References box_x, box_y, get_particles_len(), and particles.
get_next_collision_particles()
double ClassSiec::get_next_collision_particles (vector< s_pair > * pairs)
Fills the tables of the next collisions
Parameters
pairs
Returns
Definition at line 893 of file ClassSiec.cpp.
References box_x, box_y, get_particles_len(), and particles.
Referenced by step_all().
get_number_of_particles_in_radius() [1/2]
uint64_t ClassSiec::get_number_of_particles_in_radius (double r, double dr, particle * for_particle)
Get the number of particles in radius for center of particle
Parameters
r
dr
for_particle
Returns
Definition at line 1236 of file ClassSiec.cpp.
References box_x, box_y, particle::get_distance(), get_particles_len(), and particles.
Referenced by get_radial_distribution_function(), get_RDF_r(), and thread_RDF().
get_number_of_particles_in_radius() [2/2]
uint64_t ClassSiec::get_number_of_particles_in_radius (double r, double dr)
Get number of particles in radius of each particles
Parameters
r
dr
Returns
Definition at line 1262 of file ClassSiec.cpp.
References box_x, box_y, get_distance_2d(), get_particles_len(), and particles.
get_packing_ratio()
float ClassSiec::get_packing_ratio (void)
Get the packing ratio of the particles in the box
Returns
Definition at line 1197 of file ClassSiec.cpp.
References box_x, box_y, get_particles_len(), and particles.
Referenced by get_radial_distribution_function_theoretical(), get_state_space_Boublik(), get_state_space_Handerson(), get_state_space_Solan(), get_static_parameters_info(), and get_static_parameters_raw().
get_particle()
int ClassSiec::get_particle (uint64_t nr, particle * here)
Get address of particle with number to destination
Todo:
Probably useless
Parameters
nr
here
Returns
Definition at line 830 of file ClassSiec.cpp.
References ERROR, OK, and particles.
get_particles_len()
uint64_t ClassSiec::get_particles_len (void)
Returns
numbers of particles
Definition at line 415 of file ClassSiec.cpp.
References particles.
Referenced by draw_all(), fix_position(), get_density(), get_density_real(), get_kinetic_energy(), get_max_radius(), get_min_radius(), get_next_collision_particle_number(), get_next_collision_particles(), get_number_of_particles_in_radius(), get_packing_ratio(), get_RDF_r(), get_static_parameters_info(), get_temperature(), get_Velocity_Autocorrelation_Function(), save_RDF(), save_RDF_to_array(), set_mass_all(), set_mass_to_area(), set_mass_to_radius(), set_momentum_to_zero(), set_particles_zero_time(), set_random_size(), set_random_velocity(), step_all(), and thread_RDF().
get_radial_distribution_function() [1/2]
float ClassSiec::get_radial_distribution_function (double r, double dr, particle * for_particle, uint64_t prec = 100)
Get Radial distribution Function for particle
Parameters
r
dr
for_particle
prec -> divide dr into 'prec' parts zrobic histogramy dla wszystkich kulek i liczyc g(r) od (r/d) lub (r/sigma)
Returns
Definition at line 1296 of file ClassSiec.cpp.
References current_RDF, get_density(), and get_number_of_particles_in_radius().
Referenced by step_all().
get_radial_distribution_function() [2/2]
float ClassSiec::get_radial_distribution_function (double r, double dr)
Get Radial distribution Function
Bug:
probably bad function
Parameters
r
dr
Returns
Definition at line 1328 of file ClassSiec.cpp.
References get_density(), and get_number_of_particles_in_radius().
get_radial_distribution_function_theoretical()
float ClassSiec::get_radial_distribution_function_theoretical (void)
Get Radial distribution Function - theoretical
Todo:
Check this
Returns
Definition at line 1339 of file ClassSiec.cpp.
References get_packing_ratio().
Referenced by get_static_parameters_info().
get_RDF_r() [1/2]
std::string ClassSiec::get_RDF_r (double r, double dr, uint64_t prec = 100, std::string sep = " ")
Get RDF
Parameters
r
dr
prec
sep
Returns
Definition at line 1625 of file ClassSiec.cpp.
References get_density(), get_number_of_particles_in_radius(), get_particles_len(), and particles.
Referenced by get_RDF_r().
get_RDF_r() [2/2]
std::string ClassSiec::get_RDF_r (uint64_t prec = 100, std::string sep = " ")
Get default RDF
Parameters
prec
sep
Returns
Definition at line 1666 of file ClassSiec.cpp.
References box_x, box_y, and get_RDF_r().
get_state_space_Boublik()
float ClassSiec::get_state_space_Boublik (void)
Get state space - Boublik
Returns
Definition at line 1349 of file ClassSiec.cpp.
References get_density(), get_packing_ratio(), get_temperature(), and kBoltzmann.
Referenced by get_static_parameters_info(), and get_static_parameters_raw().
get_state_space_Handerson()
float ClassSiec::get_state_space_Handerson (void)
Get state space - Handerson
Returns
Definition at line 1363 of file ClassSiec.cpp.
References get_density(), get_packing_ratio(), get_temperature(), and kBoltzmann.
Referenced by get_static_parameters_info(), and get_static_parameters_raw().
get_state_space_Solan()
float ClassSiec::get_state_space_Solan (void)
Get state space - Solan
Returns
Definition at line 1374 of file ClassSiec.cpp.
References get_density(), get_packing_ratio(), get_temperature(), and kBoltzmann.
Referenced by get_static_parameters_info(), and get_static_parameters_raw().
get_static_parameters_info()
std::string ClassSiec::get_static_parameters_info (std::string sep = "\n")
Get static parameters full
Parameters
sep
Returns
Definition at line 1800 of file ClassSiec.cpp.
References get_density(), get_density_real(), get_diffusitivity_delta(), get_diffusitivity_delta_ratio(), get_diffusivity(), get_packing_ratio(), get_particles_len(), get_radial_distribution_function_theoretical(), get_state_space_Boublik(), get_state_space_Handerson(), get_state_space_Solan(), get_temperature(), and get_Velocity_Autocorrelation_Function().
Referenced by main().
get_static_parameters_raw()
std::string ClassSiec::get_static_parameters_raw (std::string sep = "\t")
Get static parameters raw data only
Parameters
sep
Returns
Definition at line 1838 of file ClassSiec.cpp.
References get_density(), get_density_real(), get_diffusitivity_delta(), get_diffusitivity_delta_ratio(), get_diffusivity(), get_packing_ratio(), get_state_space_Boublik(), get_state_space_Handerson(), get_state_space_Solan(), get_temperature(), and get_Velocity_Autocorrelation_Function().
get_static_parameters_title()
std::string ClassSiec::get_static_parameters_title (std::string sep = "\t")
Get static parameters only title
Parameters
sep
Returns
Definition at line 1769 of file ClassSiec.cpp.
get_temperature()
float ClassSiec::get_temperature (void)
Get temperature
Returns
Definition at line 1144 of file ClassSiec.cpp.
References get_particles_len(), kBoltzmann, and particles.
Referenced by get_state_space_Boublik(), get_state_space_Handerson(), get_state_space_Solan(), get_static_parameters_info(), get_static_parameters_raw(), and set_momentum_to_zero().
get_time()
float ClassSiec::get_time (void)
Definition at line 1135 of file ClassSiec.cpp.
Referenced by thread_siec().
get_Velocity_Autocorrelation_Function()
float ClassSiec::get_Velocity_Autocorrelation_Function (void)
Get Velocity Autocorrelation Function iloczyn skalarny vx(0)*vx(t)
Returns
Definition at line 1388 of file ClassSiec.cpp.
References get_particles_len(), particles, and particles_zero_time.
Referenced by get_box_info(), get_box_info_raw(), get_static_parameters_info(), get_static_parameters_raw(), get_Velocity_Autocorrelation_Function_delta_ratio(), step_all(), and thread_siec().
get_Velocity_Autocorrelation_Function_delta()
double ClassSiec::get_Velocity_Autocorrelation_Function_delta (void)
Definition at line 1431 of file ClassSiec.cpp.
References find_delta().
Referenced by get_box_info(), get_box_info_raw(), and thread_siec().
get_Velocity_Autocorrelation_Function_delta_ratio()
double ClassSiec::get_Velocity_Autocorrelation_Function_delta_ratio (void)
Get Velocity Autocorrelation Function delta ratio
Returns
Definition at line 1449 of file ClassSiec.cpp.
References find_delta(), and get_Velocity_Autocorrelation_Function().
init()
int ClassSiec::init (std::string filename)
Parameters
filename
Returns
Definition at line 953 of file ClassSiec.cpp.
References get_box_info_title(), OK, and set_particles_zero_time().
Referenced by main().
insert_to_file()
int ClassSiec::insert_to_file (std::string data)
Flush string to file
Parameters
data
Returns
Definition at line 972 of file ClassSiec.cpp.
References OK.
Referenced by main(), save_RDF(), and step_all().
save_RDF()
int ClassSiec::save_RDF (uint64_t prec = 100, std::string sep = " ")
Save default RDF to file
Parameters
prec
sep
Returns
Definition at line 1678 of file ClassSiec.cpp.
References current_RDF, get_particles_len(), insert_to_file(), OK, and thread_RDF().
save_RDF_to_array()
void ClassSiec::save_RDF_to_array (vector< double > * array, uint64_t prec = 100)
Definition at line 1711 of file ClassSiec.cpp.
References current_RDF, get_particles_len(), and thread_RDF().
Referenced by main().
set_dt()
int ClassSiec::set_dt (double dt)
Set delta time
Todo:
function is deprecated
Parameters
dt
Returns
Definition at line 394 of file ClassSiec.cpp.
References OK.
set_mass_all()
int ClassSiec::set_mass_all (double mass = 1.0)
Sets the masses for all particles
Parameters
mass
Returns
Definition at line 745 of file ClassSiec.cpp.
References get_particles_len(), OK, and particles.
Referenced by main().
set_mass_to_area()
int ClassSiec::set_mass_to_area (double ratio = 1.0)
Sets the masses according to the area of particle
Parameters
ratio
Returns
Definition at line 730 of file ClassSiec.cpp.
References get_particles_len(), OK, and particles.
set_mass_to_radius()
int ClassSiec::set_mass_to_radius (double ratio = 1.0)
Sets the masses according to the radius of particle
Parameters
ratio
Returns
Definition at line 716 of file ClassSiec.cpp.
References get_particles_len(), OK, and particles.
set_momentum_to_zero()
int ClassSiec::set_momentum_to_zero (double temperature, double precision = 0.001)
Set temperature to Ekpoz_t
Parameters
Ekpoz_t
precision
Returns
Definition at line 760 of file ClassSiec.cpp.
References find_is_in_range(), get_kinetic_energy(), get_particles_len(), get_temperature(), OK, and particles.
Referenced by main().
set_particles_zero_time()
int ClassSiec::set_particles_zero_time (void)
Saves the initial states to an individual array
Returns
Definition at line 806 of file ClassSiec.cpp.
References get_particles_len(), OK, particles, and particles_zero_time.
Referenced by init(), and main().
set_random_size()
int ClassSiec::set_random_size (double min, double max)
Set random size of particles
Parameters
min
max
Returns
Definition at line 692 of file ClassSiec.cpp.
References ERROR, get_particles_len(), OK, and particles.
set_random_velocity()
int ClassSiec::set_random_velocity (double multiplier = 1.0)
Set random velocity for all particles
Parameters
multiplier
Returns
Definition at line 668 of file ClassSiec.cpp.
References get_particles_len(), OK, and particles.
Referenced by main().
step_all()
int ClassSiec::step_all (int debug = 0)
Step all particles
Returns
Definition at line 1001 of file ClassSiec.cpp.
References box_x, box_y, particle::color, distance, distancex, distancey, fix_position(), get_box_info(), get_box_info_raw(), get_min_radius(), get_next_collision_particles(), get_particles_len(), get_radial_distribution_function(), particle::get_velocity(), get_Velocity_Autocorrelation_Function(), insert_to_file(), OK, particles, particle::pos, particle::t, th_to_box(), particle::vel, and zderzenie().
Referenced by main(), and thread_siec().
Member Data Documentation
box_x
double ClassSiec::box_x
Definition at line 200 of file ClassSiec.h.
Referenced by ClassSiec(), convert_to_box(), create_hexagonal(), create_honeycomb(), create_square(), fix_position(), get_box_x(), get_density(), get_density_real(), get_next_collision_particle_number(), get_next_collision_particles(), get_number_of_particles_in_radius(), get_packing_ratio(), get_RDF_r(), and step_all().
box_y
double ClassSiec::box_y
Definition at line 201 of file ClassSiec.h.
Referenced by ClassSiec(), convert_to_box(), create_hexagonal(), create_honeycomb(), create_square(), fix_position(), get_box_y(), get_density(), get_density_real(), get_next_collision_particle_number(), get_next_collision_particles(), get_number_of_particles_in_radius(), get_packing_ratio(), get_RDF_r(), and step_all().
current_RDF
vector<double> ClassSiec::current_RDF
Definition at line 196 of file ClassSiec.h.
Referenced by draw_RDF(), get_radial_distribution_function(), save_RDF(), save_RDF_to_array(), and thread_RDF().
distance
double ClassSiec::distance
Definition at line 199 of file ClassSiec.h.
Referenced by step_all().
distancex
double ClassSiec::distancex
Definition at line 197 of file ClassSiec.h.
Referenced by step_all().
distancey
double ClassSiec::distancey
Definition at line 198 of file ClassSiec.h.
Referenced by step_all().
particles
vector<particle> ClassSiec::particles
Definition at line 194 of file ClassSiec.h.
Referenced by add_particle(), create_hexagonal(), create_honeycomb(), draw_all(), fix_position(), get_density_real(), get_kinetic_energy(), get_max_radius(), get_min_radius(), get_next_collision_particle_number(), get_next_collision_particles(), get_number_of_particles_in_radius(), get_packing_ratio(), get_particle(), get_particles_len(), get_RDF_r(), get_temperature(), get_Velocity_Autocorrelation_Function(), set_mass_all(), set_mass_to_area(), set_mass_to_radius(), set_momentum_to_zero(), set_particles_zero_time(), set_random_size(), set_random_velocity(), step_all(), thread_RDF(), and ~ClassSiec().
particles_zero_time
vector<particle_zero_time> ClassSiec::particles_zero_time
Definition at line 195 of file ClassSiec.h.
Referenced by get_Velocity_Autocorrelation_Function(), and set_particles_zero_time().
The documentation for this class was generated from the following files:
ClassSiec.h
ClassSiec.cpp