My Project: ClassSiec.h File Reference
ClassSiec.h File Reference
#include <allegro5/color.h>
#include <bits/stdint-uintn.h>
#include <string>
#include <iomanip>
#include <cmath>
#include <sstream>
#include <vector>
#include <iostream>
#include <algorithm>
#include <set>
#include <thread>
#include <future>
#include <fstream>
#include <exception>
Classes
struct particle
struct part_particles
struct s_pair
struct particle_zero_time
class ClassSiec
Macros
#define OK 1
#define ERROR -1
#define DEBUG 1
Functions
template<class T >
T find_max (T *data, uint64_t size)
template<class T >
T find_min (T *data, uint64_t size)
template<class T >
T find_max (vector< T > *data)
template<class T >
T find_min (vector< T > *data)
template<class T >
T find_delta (vector< T > *data)
template<class T >
T find_sum (vector< T > &data)
template<class T >
T find_average (vector< T > &data)
int find_is_in_range (double value, double centrum, double delta)
int find_is_in_range (double value, double centrum, double left, double right)
int save_to_file (std::string filename, std::string data)
double get_distance_1d (double x0, double x1, double box_x)
double get_distance_2d (particle *p0, particle *p1, double box_x, double box_y)
double get_distance_2d (double x0, double y0, double x1, double y1, double box_x, double box_y)
int zderzenie (particle *cz0, particle *cz1, double box_x=0.0, double box_y=0.0)
void thread_RDF (ClassSiec *siec, uint64_t c1, double prec=100.0)
Variables
const double kBoltzmann = 1.0
Macro Definition Documentation
DEBUG
#define DEBUG 1
Definition at line 18 of file ClassSiec.h.
ERROR
#define ERROR -1
Definition at line 17 of file ClassSiec.h.
Referenced by draw_all(), draw_RDF(), ClassSiec::get_particle(), and ClassSiec::set_random_size().
OK
#define OK 1
Definition at line 16 of file ClassSiec.h.
Referenced by ClassSiec::add_particle(), ClassSiec::close_file(), ClassSiec::create_hexagonal(), ClassSiec::create_honeycomb(), ClassSiec::create_square(), draw_all(), draw_RDF(), ClassSiec::fix_position(), ClassSiec::flush_file(), ClassSiec::get_particle(), ClassSiec::init(), ClassSiec::insert_to_file(), ClassSiec::save_RDF(), save_to_file(), ClassSiec::set_dt(), particle::set_mass(), ClassSiec::set_mass_all(), ClassSiec::set_mass_to_area(), ClassSiec::set_mass_to_radius(), particle::set_maxVelocity(), ClassSiec::set_momentum_to_zero(), ClassSiec::set_particles_zero_time(), particle::set_pos(), particle::set_r(), ClassSiec::set_random_size(), ClassSiec::set_random_velocity(), particle::set_vel(), particle::step(), ClassSiec::step_all(), and zderzenie().
Function Documentation
find_average()
template<class T > T find_average (vector< T > & data)
Definition at line 79 of file ClassSiec.cpp.
find_delta()
template<class T > T find_delta (vector< T > * data)
find_is_in_range() [1/2]
int find_is_in_range (double value, double centrum, double delta)
Definition at line 103 of file ClassSiec.cpp.
Referenced by ClassSiec::create_hexagonal(), ClassSiec::create_honeycomb(), ClassSiec::set_momentum_to_zero(), and thread_siec().
find_is_in_range() [2/2]
int find_is_in_range (double value, double centrum, double left, double right)
Definition at line 108 of file ClassSiec.cpp.
find_max() [1/2]
template<class T > T find_max (T * data, uint64_t size)
Definition at line 3 of file ClassSiec.cpp.
find_max() [2/2]
template<class T > T find_max (vector< T > * data)
find_min() [1/2]
template<class T > T find_min (T * data, uint64_t size)
Definition at line 12 of file ClassSiec.cpp.
find_min() [2/2]
template<class T > T find_min (vector< T > * data)
find_sum()
template<class T > T find_sum (vector< T > & data)
Definition at line 69 of file ClassSiec.cpp.
get_distance_1d()
double get_distance_1d (double x0, double x1, double box_x)
Calculate the distance in box
Parameters
x0
x1
box_x
Returns
Definition at line 228 of file ClassSiec.cpp.
Referenced by particle::get_distance(), get_distance_2d(), particle::get_time_to_collision(), and zderzenie().
get_distance_2d() [1/2]
double get_distance_2d (particle * p0, particle * p1, double box_x, double box_y)
Calculate distance in 2D in box
Parameters
p0
p1
box_x
box_y
Returns
Definition at line 246 of file ClassSiec.cpp.
References get_distance_1d(), and particle::pos.
Referenced by ClassSiec::get_number_of_particles_in_radius().
get_distance_2d() [2/2]
double get_distance_2d (double x0, double y0, double x1, double y1, double box_x, double box_y)
Calculate distance in 2D in box
Parameters
x0
y0
x1
y1
box_x
box_y
Returns
Definition at line 263 of file ClassSiec.cpp.
References get_distance_1d().
save_to_file()
int save_to_file (std::string filename, std::string data)
Save to file
Parameters
filename
data
Returns
Definition at line 1497 of file ClassSiec.cpp.
References OK.
thread_RDF()
void thread_RDF (ClassSiec * siec, uint64_t c1, double prec)
Thread for RDF
Parameters
siec
c1
prec
Definition at line 1748 of file ClassSiec.cpp.
References ClassSiec::current_RDF, ClassSiec::get_density(), ClassSiec::get_min_radius(), ClassSiec::get_number_of_particles_in_radius(), ClassSiec::get_particles_len(), and ClassSiec::particles.
Referenced by ClassSiec::save_RDF(), and ClassSiec::save_RDF_to_array().
zderzenie()
int zderzenie (particle * cz0, particle * cz1, double box_x, double box_y)
Make collision of particles
Parameters
cz0
cz1
box_x
box_y
Returns
Definition at line 1101 of file ClassSiec.cpp.
References particle::color, particle::get_distance(), get_distance_1d(), particle::m, OK, particle::pos, particle::tlc, and particle::vel.
Referenced by ClassSiec::step_all().
Variable Documentation
kBoltzmann
const double kBoltzmann = 1.0
Definition at line 21 of file ClassSiec.h.
Referenced by ClassSiec::get_state_space_Boublik(), ClassSiec::get_state_space_Handerson(), ClassSiec::get_state_space_Solan(), and ClassSiec::get_temperature().