My Project: main.cpp File Reference
main.cpp File Reference
#include <allegro5/allegro.h>
#include <allegro5/allegro_primitives.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_ttf.h>
#include <allegro5/allegro_image.h>
#include <allegro5/allegro_color.h>
#include <allegro5/allegro5.h>
#include <cstdio>
#include <iostream>
#include <cstdlib>
#include <thread>
#include <string>
#include "ClassSiec.h"
Functions
template<class T >
T find_max (vector< T > &data)
template<class T >
T find_min (vector< T > &data)
template<class T >
T find_max_ignore_inf (vector< T > &data)
template<class T >
T find_min_ignore_inf (vector< T > &data)
void thread_siec (ClassSiec *siec, int *debug, int *th_run, double *stability_time, double *stability_time_full, std::string *info_text)
void pend_event (ClassSiec *siec, int *th_run, bool *redraw, ALLEGRO_EVENT_QUEUE *event_queue, ALLEGRO_EVENT *ev)
void thread_draw (ClassSiec *siec, int *th_run, bool *redraw, ALLEGRO_DISPLAY *display, ALLEGRO_BITMAP *bitmap_box, ALLEGRO_BITMAP *bitmap_RDF, std::string *info, ALLEGRO_FONT *font, double windowy)
int draw_RDF (ClassSiec *siec, ALLEGRO_BITMAP *bitmap, std::string info, ALLEGRO_FONT *font)
int draw_all (ClassSiec *siec, ALLEGRO_BITMAP *bitmap)
int main (int argc, char **argv)
Variables
uint64_t licznik = 0
Function Documentation
draw_all()
int draw_all (ClassSiec * siec, ALLEGRO_BITMAP * bitmap)
Draw all particles
Parameters
siec
bitmap
Returns
Definition at line 293 of file main.cpp.
References particle::color, ERROR, ClassSiec::get_box_x(), ClassSiec::get_box_y(), ClassSiec::get_particles_len(), OK, ClassSiec::particles, particle::pos, particle::r, and particle::vel.
Referenced by main(), and thread_draw().
draw_RDF()
int draw_RDF (ClassSiec * siec, ALLEGRO_BITMAP * bitmap, std::string info, ALLEGRO_FONT * font)
Draw RDF below particles
Parameters
siec
bitmap
Returns
Definition at line 256 of file main.cpp.
References ClassSiec::current_RDF, ERROR, and OK.
Referenced by thread_draw().
find_max()
template<class T > T find_max (vector< T > & data)
Definition at line 330 of file main.cpp.
find_max_ignore_inf()
template<class T > T find_max_ignore_inf (vector< T > & data)
Definition at line 343 of file main.cpp.
Referenced by main().
find_min()
template<class T > T find_min (vector< T > & data)
Definition at line 389 of file main.cpp.
find_min_ignore_inf()
template<class T > T find_min_ignore_inf (vector< T > & data)
Definition at line 366 of file main.cpp.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 39 of file main.cpp.
References ClassSiec::close_file(), ClassSiec::create_honeycomb(), draw_all(), find_max_ignore_inf(), find_min_ignore_inf(), ClassSiec::fix_position(), ClassSiec::flush_file(), ClassSiec::get_min_radius(), ClassSiec::get_static_parameters_info(), ClassSiec::init(), ClassSiec::insert_to_file(), licznik, pend_event(), ClassSiec::save_RDF_to_array(), ClassSiec::set_mass_all(), ClassSiec::set_momentum_to_zero(), ClassSiec::set_particles_zero_time(), ClassSiec::set_random_velocity(), ClassSiec::step_all(), thread_draw(), and thread_siec().
pend_event()
void pend_event (ClassSiec * siec, int * th_run, bool * redraw, ALLEGRO_EVENT_QUEUE * event_queue, ALLEGRO_EVENT * ev)
Definition at line 207 of file main.cpp.
Referenced by main().
thread_draw()
void thread_draw (ClassSiec * siec, int * th_run, bool * redraw, ALLEGRO_DISPLAY * display, ALLEGRO_BITMAP * bitmap_box, ALLEGRO_BITMAP * bitmap_RDF, std::string * info, ALLEGRO_FONT * font, double windowy)
Definition at line 230 of file main.cpp.
References draw_all(), and draw_RDF().
Referenced by main().
thread_siec()
void thread_siec (ClassSiec * siec, int * debug, int * th_run, double * stability_time, double * stability_time_full, std::string * info_text)
Definition at line 171 of file main.cpp.
References find_is_in_range(), ClassSiec::flush_file(), ClassSiec::get_diffusitivity_delta(), ClassSiec::get_time(), ClassSiec::get_Velocity_Autocorrelation_Function(), ClassSiec::get_Velocity_Autocorrelation_Function_delta(), and ClassSiec::step_all().
Referenced by main().
Variable Documentation
licznik
uint64_t licznik = 0
Definition at line 24 of file main.cpp.
Referenced by main().